#!/usr/bin/env python3

import os
import json

# Load JSON config
configfile: "config.json"

slurm       = config["slurm"]
QueryPath   = config["QueryPath"]
SaveFolder  = config["SaveFolder"]
ScriptFolder= config["ScriptFolder"]

os.makedirs(SaveFolder, exist_ok=True)

# Build queries dictionary dynamically from QueryPath
queries = {}
with open(QueryPath, mode='r') as f:
    for line in f:
        line = line.split()
        queries[line[1]] = line[0]
        
wksamples = list(queries.values())
assemblies = list(queries.keys())
assem_by_base = {os.path.basename(p): p for p in assemblies}


rule all:
    input:
        fasta = [os.path.join(SaveFolder, os.path.basename(prefix)) + "_maskcheckfix4" for prefix in assemblies]
        
rule assem:
    input:
        assem = lambda wc: ancient(assem_by_base[wc.base])
    params:
        qpath  = QueryPath,
        script = ScriptFolder,
    resources:
        mem_mb=3000,
        slurm_extra="--mem=3G -c 1 "
    threads: 1
    output:
        check = os.path.join(SaveFolder, "{base}_maskcheckfix4")
    run:
        filename = os.path.basename(input.assem)
        
        shell(" windowmasker -mk_counts -in {input.assem} -out outputs/{filename}_maskinfo ")
        
        shell(" windowmasker -ustat outputs/{filename}_maskinfo -dust yes -outfmt fasta -in {input.assem} -out outputs/{filename} ")
        
        prefix = queries.get(input.assem, "").replace("_h", "#")
        if len(prefix) and prefix not in ["CHM13_h1", "HG38_h1"]:
            shell(" python {params.script}/namecontigsfix.py -i outputs/{filename} -n {prefix} -o outputs/{filename}_ ")
            shell(" mv outputs/{filename}_ outputs/{filename} ")
            
        shell("samtools faidx outputs/{filename}")
        shell("touch {output.check}")
