#!/bin/bash
# Usage: runmakeblastdb -in <input.fa> -out <basename>

while [[ $# -gt 0 ]]; do
  case $1 in
    -in)
      input="$2"
      shift 2
      ;;
    -out)
      out="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

if [[ -z "$input" || -z "$out" ]]; then
  echo "Usage: runmakeblastdb -in <input.fa> -out <output_db>"
  exit 1
fi

# Run makeblastdb without -parse_seqids
makeblastdb -in "$input" -dbtype nucl -blastdb_version 5 -out "$out"

# Extract headers (full line, no truncation)
grep "^>" "$input" | sed 's/^>//' | cut  -f1 | cut -d' ' -f1 > "$out.seq"

